---
vault_bootstrap_admin_user: ""
vault_apps_admin_user: ""
vault_apps_domainname: ""

# --- proxmox ---------------------------------------------------------------
vault_proxmox_api_host: ""
vault_proxmox_api_user: "root@pam"
vault_proxmox_api_password: ""
vault_proxmox_ssh_user: "root"
vault_proxmox_ssh_pass: ""

# --- cloudflare / traefik --------------------------------------------------
vault_apps_cloudflare_dns_api_token: ""
vault_apps_http_username: ""
vault_apps_http_password: ""

# --- authentik -------------------------------------------------------------
vault_apps_authentik_secret_key: ""
vault_apps_authentik_pg_user: ""
vault_apps_authentik_pg_name: ""
vault_apps_authentik_pg_password: ""

# --- nextcloud -------------------------------------------------------------
vault_apps_nextcloud_db_root_password: ""
vault_apps_nextcloud_db_password: ""
vault_apps_nextcloud_admin_user: ""
vault_apps_nextcloud_admin_password: ""

# --- smb / truenas ---------------------------------------------------------
vault_apps_smb_username: ""
vault_apps_smb_password: ""

# --- gamepanel (optional) --------------------------------------------------
vault_apps_gamepanel_db_password: ""
vault_apps_gamepanel_db_root_password: ""
vault_apps_gamepanel_email: ""
vault_apps_gamepanel_mail_password: ""
vault_apps_game_db_password: ""
vault_apps_game_db_root_password: ""
