---
- name: Install Ansible Galaxy roles
  hosts: localhost
  become: false
  tasks:
    - name: Install required roles
      command: ansible-galaxy install -r requirements.yml -p galaxy_roles
      register: result
      ignore_errors: true

    - name: Debug role installation result
      debug:
        var: result
