---
# Shared, non-secret, environment-independent.
# Anything environment-specific belongs in group_vars/<env>/
# Anything host-specific belongs in host_vars/<host>/
# Anything secret belongs in group_vars/<env>/vault.yml

apps_tz: "Asia/Jerusalem"
apps_puid: 1000
apps_pgid: 1000

bootstrap_admin_user: "{{ vault_bootstrap_admin_user }}"

apps_local_ips: >-
  127.0.0.1/32,10.0.0.0/8,192.168.0.0/16,172.16.0.0/12
apps_cloudflare_ips: >-
  173.245.48.0/20,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,141.101.64.0/18,108.162.192.0/18,190.93.240.0/20,188.114.96.0/20,197.234.240.0/22,198.41.128.0/17,162.158.0.0/15,104.16.0.0/13,104.24.0.0/14,172.64.0.0/13,131.0.72.0/22

apps_admin_user: "{{ vault_apps_admin_user | default(bootstrap_admin_user) }}"

docker_networks:
  - { name: t3_proxy, subnet: "192.168.90.0/24" }
  - { name: socket_proxy, subnet: "192.168.91.0/24" }

compose_remove_orphans: false
