---
# Infrastructure Provisioning
apps_provision_infrastructure: false
apps_vm_name: "app-server"
apps_vm_cores: 4
apps_vm_memory: 16384
apps_vm_disk_size: 120
apps_force_recreate: false

apps_admin_user: "{{ vault_apps_admin_user }}"
# ansible-role-traefik/defaults/main.yml
apps_traefik_version: v2.5.4
apps_traefik_data_folder: /home/{{ apps_admin_user }}/traefik
apps_puid: 1000
apps_pgid: 1000
apps_tz: "Asia/Jerusalem"
apps_userdir: "/home/{{ apps_admin_user }}"
apps_dockerdir: "/home/{{ apps_admin_user }}/docker"
apps_datadir: "/media/workgroup"
apps_hostname: "prod-app"
apps_cloudflare_dns_api_token: "{{ vault_apps_cloudflare_dns_api_token }}"
apps_domainname: "{{ vault_apps_domainname }}"
apps_local_ips: "127.0.0.1/32,10.0.0.0/8,192.168.0.0/16,172.16.0.0/12,192.168.14.0/12"
apps_cloudflare_ips: "173.245.48.0/20,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,141.101.64.0/18,108.162.192.0/18,\
  190.93.240.0/20,188.114.96.0/20,197.234.240.0/22,198.41.128.0/17,162.158.0.0/15,104.16.0.0/13,104.24.0.0/14,\
  172.64.0.0/13,131.0.72.0/22"
apps_http_username: "{{ vault_apps_http_username }}"
apps_http_password: "{{ vault_apps_http_password }}"
apps_docker_privileged_mode: true
apps_use_staging: false # Set to true to use staging certificates
apps_reset_acme: false # Set to true to reset the acme.json file
apps_reset_logs: false # Set to true to reset the logs
apps_enabled_apps: # comment out if you dont want certain applications
  - socket-proxy
  - traefik
  - portainer
  #  - gamepanel
  - cloudflare-ddns
  - authentik
  - it-tools
#  - nextcloud
#  - kasm

# Game Panel Role Variables
apps_gamepanel_db_name: panel
apps_gamepanel_db_user: pterodactyl
apps_gamepanel_db_password: "{{ vault_apps_gamepanel_db_password }}"
apps_gamepanel_db_root_password: "{{ vault_apps_gamepanel_db_root_password }}"
apps_gamepanel_timezone: Asia/Jerusalem
apps_gamepanel_domain: "panel.{{ apps_domainname }}"
apps_gamepanel_email: "{{ vault_apps_gamepanel_email }}"
apps_gamepanel_mail_host: "mail.{{ apps_domainname }}"
apps_gamepanel_mail_port: 587
apps_gamepanel_mail_password: "{{ vault_apps_gamepanel_mail_password }}"
apps_gamepanel_wings_domain: "wings0.{{ apps_domainname }}"
apps_gamepanel_uid: "1000"
apps_gamepanel_gid: "1000"
apps_gamepanel_wings_user: pterodactyl
apps_gamepanel_wings_subnet: "172.50.0.0/16"
apps_game_db_name: game
apps_game_db_user: game
apps_game_db_password: "{{ vault_apps_game_db_password }}"
apps_game_db_root_password: "{{ vault_apps_game_db_root_password }}"

## authentik
apps_authentik_pg_user: "{{ vault_apps_authentik_pg_user }}"
apps_authentik_pg_password: "{{ vault_apps_authentik_pg_password }}"
apps_authentik_pg_name: "{{ vault_apps_authentik_pg_name }}"
apps_authentik_secret_key: "{{ vault_apps_authentik_secret_key }}"
apps_reset_authentik: false

# Nextcloud Role Variables
apps_nextcloud_db_root_password: "{{ vault_apps_nextcloud_db_root_password }}"
apps_nextcloud_db_password: "{{ vault_apps_nextcloud_db_password }}"
apps_nextcloud_admin_user: "{{ vault_apps_nextcloud_admin_user }}"
apps_nextcloud_admin_password: "{{ vault_apps_nextcloud_admin_password }}"
apps_nextcloud_trusted_domain: "nextcloud.{{ apps_domainname }}"
apps_nextcloud_update: false # Set to true to enable Nextcloud update on container startup
apps_nextcloud_trusted_proxies: 192.168.90.254 traefik # Add any additional trusted proxies here
apps_nextcloud_reset: true

## workgroup\nextcloud SMB mount
apps_smb_share: //truenas.lan/workgroup
apps_smb_mountpoint: /media/workgroup # This should be the base directory for autofs
apps_smb_credentials_file: /etc/auto.workgroupcredentials
apps_smb_username: "{{ vault_apps_smb_username }}"
apps_smb_password: "{{ vault_apps_smb_password }}"
