---
- name: Install Ansible Galaxy roles
  hosts: localhost
  become: false
  tasks:
    - name: Remove existing roles directory
      file:
        path: "./roles"
        state: absent

    - name: Ensure roles directory exists
      file:
        path: "./roles"
        state: directory

    - name: Install required roles
      command: ansible-galaxy install -r requirements.yml -f
      register: result
      ignore_errors: true

    - name: Debug role installation result
      debug:
        var: result
