---
- name: Copy Docker Compose files for enabled apps
  become: true
  ansible.builtin.template:
    src: "services/docker-compose.{{ item }}.yml.j2"
    dest: "{{ apps_dockerdir }}/docker-compose.{{ item }}.yml"
    owner: "{{ apps_admin_user }}"
    group: "{{ apps_admin_user }}"
    mode: "0640"
  loop: "{{ apps_enabled_apps }}"
  tags: compose_file

- name: Copy .env file
  become: true
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ apps_dockerdir }}/.env"
    owner: root
    group: root
    mode: "0640"
  with_fileglob:
    - "{{ role_path }}/templates/services/.env"
  tags: compose_file

- name: Start Docker Compose stack
  become: true
  community.docker.docker_compose_v2:
    project_src: "{{ apps_dockerdir }}"
    files: "{{ apps_enabled_apps | map('regex_replace', '(.*)', 'docker-compose.\\1.yml') | list }}"
    state: present
    remove_orphans: true
  tags: docker_compose
